name: Testing CI

on:
  pull_request:
  push:
    paths:
      - .github/workflows/**/*.yaml

env:
  WASM_SOURCES_PATH: './test/examples'
  WASM_BINARIES_PATH: './test/examples'
  WASM_BINARIES_PATH_WIN: '.\test\examples'
  WASM_MODULE_NAME: 'example'

jobs:
  build_wasm_artifacts--rust:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Get 'wasm-pack' tool from cache ...
        uses: actions/cache@v3
        id: cache-wasm-pack
        with:
          path: ~/.cargo/bin/wasm-pack
          key: ${{ runner.os }}-wasm-pack

      - name: ... or install and cache 'wasm-pack' tool
        if: ${{ steps.cache-wasm-pack.outputs.cache-hit != 'true' }}
        run: cargo install wasm-pack

      - uses: actions/checkout@v3
      - run: |
          cd ${{ env.WASM_SOURCES_PATH }}/Rust
          wasm-pack build --target nodejs
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts--rust
          path: ${{ env.WASM_SOURCES_PATH }}/Rust/target/wasm32-unknown-unknown/release/${{ env.WASM_MODULE_NAME }}.wasm

  build_wasm_artifacts--cpp:
    runs-on: ubuntu-latest
    env:
      EM_VERSION: 3.1.44
    steps:
      - uses: actions/checkout@v3

      - name: Get 'emscripten-sdk' from cache ...
        uses: actions/cache@v3
        id: cache-emscripten-sdk
        with:
          path: emsdk/
          key: emscripten-sdk-${{ env.EM_VERSION }}${{ runner.os }}-wasm-pack

      - name: ... or install and cache 'emscripten-sdk'
        if: ${{ steps.cache-emscripten-sdk.outputs.cache-hit != 'true' }}
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ env.EM_VERSION }}
          ./emsdk activate ${{ env.EM_VERSION }}

      - run: |
          source ./emsdk/emsdk_env.sh
          cd ${{ env.WASM_SOURCES_PATH }}/C++
          em++ -std=c++11 ${{ env.WASM_MODULE_NAME }}.cpp  -Os -s WASM=1 -s SIDE_MODULE=1 -o ${{ env.WASM_MODULE_NAME }}.wasm

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts--cpp
          path: ${{ env.WASM_SOURCES_PATH }}/C++/${{ env.WASM_MODULE_NAME }}.wasm

  build_wasm_artifacts--as:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get AssemblyScript deps from cache ...
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.WASM_SOURCES_PATH }}/AssemblyScript/node_modules/
          key: AssemblyScript-node_modules-${{ hashFiles(format('{0}/AssemblyScript/package-lock.json', env.WASM_SOURCES_PATH)) }}

      - name: ... or install and cache AssemblyScript deps
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.WASM_SOURCES_PATH }}/AssemblyScript
          npm i

      - run: |
          cd ${{ env.WASM_SOURCES_PATH }}/AssemblyScript
          npx asc ${{ env.WASM_MODULE_NAME }}.ts --outFile ${{ env.WASM_MODULE_NAME }}.wasm --optimize

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts--as
          path: ${{ env.WASM_SOURCES_PATH }}/AssemblyScript/${{ env.WASM_MODULE_NAME }}.wasm

  lint_and_test:
    needs:
      - build_wasm_artifacts--rust
      - build_wasm_artifacts--cpp
      - build_wasm_artifacts--as

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node:
          - 16
          - 18
          - 19
          - 20
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download WASM binaries
        uses: actions/download-artifact@v3

      - name: Move binaries to proper directory
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          rm ${{ env.WASM_BINARIES_PATH}}/rust.wasm
          mv artifacts--rust/${{ env.WASM_MODULE_NAME }}.wasm ${{ env.WASM_BINARIES_PATH}}/rust.wasm
          rm -r artifacts--rust

          rm ${{ env.WASM_BINARIES_PATH}}/cpp.wasm
          mv artifacts--cpp/${{ env.WASM_MODULE_NAME }}.wasm ${{ env.WASM_BINARIES_PATH}}/cpp.wasm
          rm -r artifacts--cpp

          rm ${{ env.WASM_BINARIES_PATH}}/as.wasm
          mv artifacts--as/${{ env.WASM_MODULE_NAME }}.wasm ${{ env.WASM_BINARIES_PATH}}/as.wasm
          rm -r artifacts--as

      - name: Move binaries to proper directory (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Remove-Item -Path ${{ env.WASM_BINARIES_PATH_WIN }}\rust.wasm
          Move-Item -Path artifacts--rust\${{ env.WASM_MODULE_NAME }}.wasm -Destination ${{ env.WASM_BINARIES_PATH_WIN }}\rust.wasm
          Remove-Item -Path artifacts--rust -Recurse

          Remove-Item -Path ${{ env.WASM_BINARIES_PATH_WIN }}\cpp.wasm
          Move-Item -Path artifacts--cpp\${{ env.WASM_MODULE_NAME }}.wasm -Destination ${{ env.WASM_BINARIES_PATH_WIN }}\cpp.wasm
          Remove-Item -Path artifacts--cpp -Recurse

          Remove-Item -Path ${{ env.WASM_BINARIES_PATH_WIN }}\as.wasm
          Move-Item -Path artifacts--as\${{ env.WASM_MODULE_NAME }}.wasm -Destination ${{ env.WASM_BINARIES_PATH_WIN }}\as.wasm
          Remove-Item -Path artifacts--as -Recurse

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm test
